! (C) Copyright 2015- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.




MODULE RADIATION_SCHEME_LAYER_MOD

IMPLICIT NONE

PRIVATE
PUBLIC :: RADIATION_SCHEME_LAYER, RADIATION_SCHEME_LAYER_PARALLEL

CONTAINS

SUBROUTINE RADIATION_SCHEME_LAYER &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
     &  NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED)

! Modules from ifs or ifsaux libraries
USE RADIATION_SETUP , ONLY : TRADIATION
USE PARKIND1        , ONLY : JPIM, JPRB
USE RADINTG_ZRGP_MOD, ONLY : RADINTG_ZRGP_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION)   ,INTENT(IN), TARGET :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NRPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: NFSD
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER, OPTIONAL, INTENT(IN)   :: ISEED(:,:)

CALL RADIATION_SCHEME_LAYER_PARALLEL( &
    & YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
    & NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED=ISEED )

END SUBROUTINE RADIATION_SCHEME_LAYER

SUBROUTINE RADIATION_SCHEME_LAYER_PARALLEL &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
     &  NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED)

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE

! Modules from ifs or ifsaux libraries
USE RADIATION_SETUP , ONLY : TRADIATION
USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE RADINTG_ZRGP_MOD, ONLY : RADINTG_ZRGP_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION)   ,INTENT(IN), TARGET :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NRPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: NFSD
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER, OPTIONAL, INTENT(IN)   :: ISEED(:,:)

INTEGER(KIND=JPIM) :: KIDIA, KFDIA, IBL, JKGLO

! Dummies for IFS config values
LOGICAL :: LSPPRAD, LRAYFM, LEPO3RA
LOGICAL, PARAMETER :: LDEBUG = .false.

! Field pointers for each field in ZRGP
CLASS(FIELD_2RB), POINTER :: F_igi => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igi(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_imu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_imu0(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iamu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iamu0(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iemiss => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemiss(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_its => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_its(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islm => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islm(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccnl => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccnl(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccno => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccno(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ibas => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ibas(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itop => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itop(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igelam => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igelam(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igemu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igemu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iclon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclon(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islon(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iald => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iald(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ialp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ialp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ipr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ipr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iqs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iqs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iwv => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iwv(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iclc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iiwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iiwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irra => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irra(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_idp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_idp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioz => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioz(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iecpo3 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iecpo3(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihpr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihpr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaprs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaprs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_liq => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_liq(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_ice => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_ice(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioverlap => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioverlap(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaero => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaero(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsod => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsod(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrted => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrted(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsodc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsodc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrtedc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrtedc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iemit => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemit(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_isudu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_isudu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iuvdf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iuvdf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparcf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparcf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itincf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itincf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdir(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdif => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdif(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_icdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icdir(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwderivative => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwderivative(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdirectband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdirectband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdiffuseband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdiffuseband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrso => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrso(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrth => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrth(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaer => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaer(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iico2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iico2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iich4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iich4(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iin2o => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iin2o(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ino2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ino2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic11 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic11(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic12 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic12(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic22 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic22(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_icl4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icl4(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igix => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igix(:) => NULL()

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "radiation_scheme.intfb.h"

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_PARALLEL',0,ZHOOK_HANDLE)

ASSOCIATE(YDERAD=>YRADIATION%YRERAD, RAD_CONFIG=>YRADIATION%RAD_CONFIG)
ASSOCIATE(LDIAGFORCING=>YDERAD%LDIAGFORCING, LAPPROXLWUPDATE=>YDERAD%LAPPROXLWUPDATE, &
    & LAPPROXSWUPDATE=>YDERAD%LAPPROXSWUPDATE, NRADAER=>RAD_CONFIG%N_AEROSOL_TYPES)

LSPPRAD=.FALSE.
    KIDIA=1
    KFDIA=MIN(NRPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NRPROMA+1

    P_iamu0 => F_iamu0%GET_VIEW(IBL)
    P_its => F_its%GET_VIEW(IBL)
    P_iald => F_iald%GET_VIEW(IBL)
    P_ialp => F_ialp%GET_VIEW(IBL)
    P_iemiss => F_iemiss%GET_VIEW(IBL)
    P_iccnl => F_iccnl%GET_VIEW(IBL)
    P_iccno => F_iccno%GET_VIEW(IBL)
    P_igelam => F_igelam%GET_VIEW(IBL)
    P_igemu => F_igemu%GET_VIEW(IBL)
    P_islm => F_islm%GET_VIEW(IBL)
    P_ipr => F_ipr%GET_VIEW(IBL)
    P_iti => F_iti%GET_VIEW(IBL)
    P_iaprs => F_iaprs%GET_VIEW(IBL)
    P_ihti => F_ihti%GET_VIEW(IBL)
    P_iwv => F_iwv%GET_VIEW(IBL)
    P_iico2 => F_iico2%GET_VIEW(IBL)
    P_iich4 => F_iich4%GET_VIEW(IBL)
    P_iin2o => F_iin2o%GET_VIEW(IBL)
    P_ino2 => F_ino2%GET_VIEW(IBL)
    P_ic11 => F_ic11%GET_VIEW(IBL)
    P_ic12 => F_ic12%GET_VIEW(IBL)
    P_ic22 => F_ic22%GET_VIEW(IBL)
    P_icl4 => F_icl4%GET_VIEW(IBL)
    P_ioz => F_ioz%GET_VIEW(IBL)
    P_iclc => F_iclc%GET_VIEW(IBL)
    P_ilwa => F_ilwa%GET_VIEW(IBL)
    P_iiwa => F_iiwa%GET_VIEW(IBL)
    P_irwa => F_irwa%GET_VIEW(IBL)
    P_iswa => F_iswa%GET_VIEW(IBL)
    P_iaer => F_iaer%GET_VIEW(IBL)
    P_iaero => F_iaero%GET_VIEW(IBL)
    P_iaero => F_iaero%GET_VIEW(IBL)
    P_ifrso => F_ifrso%GET_VIEW(IBL)
    P_ifrth => F_ifrth%GET_VIEW(IBL)
    P_iswfc => F_iswfc%GET_VIEW(IBL)
    P_ilwfc => F_ilwfc%GET_VIEW(IBL)
    P_ifrsod => F_ifrsod%GET_VIEW(IBL)
    P_ifrted => F_ifrted%GET_VIEW(IBL)
    P_ifrsodc => F_ifrsodc%GET_VIEW(IBL)
    P_ifrtedc => F_ifrtedc%GET_VIEW(IBL)
    P_ifdir => F_ifdir%GET_VIEW(IBL)
    P_icdir => F_icdir%GET_VIEW(IBL)
    P_isudu => F_isudu%GET_VIEW(IBL)
    P_iuvdf => F_iuvdf%GET_VIEW(IBL)
    P_iparf => F_iparf%GET_VIEW(IBL)
    P_iparcf => F_iparcf%GET_VIEW(IBL)
    P_itincf => F_itincf%GET_VIEW(IBL)
    P_iemit => F_iemit%GET_VIEW(IBL)
    P_ilwderivative => F_ilwderivative%GET_VIEW(IBL)
    P_iswdiffuseband => F_iswdiffuseband%GET_VIEW(IBL)
    P_iswdirectband => F_iswdirectband%GET_VIEW(IBL)
    P_ire_liq => F_ire_liq%GET_VIEW(IBL)
    P_ire_ice => F_ire_ice%GET_VIEW(IBL)
    P_ioverlap => F_ioverlap%GET_VIEW(IBL)

    ! Call the ECRAD radiation scheme
    CALL RADIATION_SCHEME &
        & (YRADIATION, &
        &  KIDIA, KFDIA, NRPROMA, &                       ! startcol, endcol, ncol
        &  NFLEVG, KAEROSOL, &
        &  PSOLAR_IRRADIANCE, &                               ! solar_irrad
        &  P_IAMU0, P_ITS, P_IALD, P_IALP, &
        &  P_IEMISS, &
        &  P_ICCNL, P_ICCNO ,&
        &  P_IGELAM,P_IGEMU, P_ISLM, &
        &  P_IPR, P_ITI, &
        &  P_IAPRS,P_IHTI, &
        &  P_IWV,P_IICO2,P_IICH4,P_IIN2O, &
        &  P_INO2,P_IC11,P_IC12, P_IC22, &
        &  P_ICL4,P_IOZ, &
        &  P_ICLC,P_ILWA,P_IIWA,P_IRWA, &
        &  P_ISWA, &
        &  P_IAER, P_IAERO, &
        ! Flux outputs
        &  P_IFRSO,P_IFRTH,P_ISWFC,P_ILWFC,&
        &  P_IFRSOD,P_IFRTED, &
        &  P_IFRSODC,P_IFRTEDC,&
        &  P_IFDIR,P_ICDIR,P_ISUDU, &
        &  P_IUVDF,P_IPARF, &
        &  P_IPARCF,P_ITINCF, &
        &  P_IEMIT,P_ILWDERIVATIVE, &
        &  P_ISWDIFFUSEBAND,P_ISWDIRECTBAND &
        ! OPTIONAL ARGUMENTS
#ifdef BITIDENTITY_TESTING
        &  , PRE_LIQ=P_IRE_LIQ, PRE_ICE=P_IRE_ICE &
        &  , PCLOUD_OVERLAP=P_IOVERLAP, ISEED=ISEED(:,IBL) &
#endif
        &  )

END DO
!$OMP END DO
!$OMP END PARALLEL

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_PARALLEL',1,ZHOOK_HANDLE)

END SUBROUTINE RADIATION_SCHEME_LAYER_PARALLEL

END MODULE RADIATION_SCHEME_LAYER_MOD
